# Generated by Django 6.1.1 on 2026-10-05 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="class_name",
            field=models.CharField(blank=True, max_length=50, verbose_name="クラス名"),
        ),
    ]
