# Generated by Django 6.1.1 on 2026-10-05 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_student_class_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="class_name",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sakura", "さくら組"),
                    ("himawari", "ひまわり組"),
                    ("bara", "ばら組"),
                    ("yuri", "ゆり組"),
                    ("tanpopo", "たんぽぽ組"),
                ],
                max_length=50,
                verbose_name="クラス名",
            ),
        ),
    ]
