# Generated by Django 6.1.1 on 2026-10-06 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_alter_student_class_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentFacePhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        upload_to="student_faces/", verbose_name="追加の顔写真"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="face_photos",
                        to="attendance.student",
                    ),
                ),
            ],
        ),
    ]
